### ISSUE TITLE
Implement embedded fields

### ISSUE THREAD

**Issue by Crevil** [jonbodner/proteus#10]
When defining the DAO struct it would be great to be able to split it up into multiple structs and embed them.

```go
type BaseDao struct {
  FindAll func(e proteus.Querier) ([]Type, error) `proq:"SELECT * FROM table"`
  CustomDao
}
type CustomDao struct {
  FindCustom func(e proteus.Querier, id string) (Type, error) `proq:"SELECT * FROM table WHERE id = :id:" prop:"id"`
}
```

The use case for us is as follows. We generate some standard functionality in the `BaseDao` stuct and would like to be able to regenerate this, without loosing the custom functionality added by `CustomDao`.

Is this possible with the reflection API? If you have some guidance to where this could be done, I'd be happy to contribute.

**Comment by jonbodner** [comment]
Yeah, this shouldn't be too hard to add. In proteus.Build, (after line 67) you'd need to check to see if a field is embedded and is a struct. You'd then recurse, passing in a pointer to the embedded struct.

Good idea. If you can implement it (and add in a test, something that is sorely lacking from the code base), that'd be great. If not, I'll try to get to it soon.

**Comment by Crevil** [comment]
Great. I'll look into it. I'm not that familiar with the `reflect` package, so give me some time and I should come up with something.
