### ISSUE TITLE
racey when benched ?

### ISSUE THREAD

**Issue by joeblew99** [jonbodner/proteus#2]
x-MacBook-Pro:bench apple$ go get github.com/mattn/go-sqlite3
x-MacBook-Pro:bench apple$ go test -bench=.
WARN[0000] skipping function FindById due to error: the 1st output parameter of an Executor must be int64 
BenchmarkSelectProteus-4   	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x41a3553]

goroutine 6 [running]:
github.com/jonbodner/proteus/bench.BenchmarkSelectProteus(0xc420012160)
	/Users/apple/workspace/go/src/github.com/jonbodner/proteus/bench/bench_test.go:33 +0x2b3
testing.(*B).runN(0xc420012160, 0x1)
	/usr/local/opt/go/libexec/src/testing/benchmark.go:140 +0xb2
testing.(*B).run1.func1(0xc420012160)
	/usr/local/opt/go/libexec/src/testing/benchmark.go:213 +0x5a
created by testing.(*B).run1
	/usr/local/opt/go/libexec/src/testing/benchmark.go:214 +0x7f
exit status 2
FAIL	github.com/jonbodner/proteus/bench	0.041s

--

THis SQL driver is buggy.
there is a better one now. See here :)

https://github.com/gobuffalo/buffalo/issues/372

**Comment by jonbodner** [comment]
Thanks! Sqlite is only used for a test case, but I'll swap to a better driver as soon as I get the chance.

**Comment by jonbodner** [comment]
The latest push replaces the original sqlite driver with the one used by buffalo. Thanks for pointing it out!
