### ISSUE TITLE
Support for RETURNING "id" queries

### ISSUE THREAD

**Issue by michaelgmiller** [jonbodner/proteus#29]
I have an INSERT query that creates a new row on an autoincrement table. Is there any way to have a RETURNING "id" suffix to the query and get the new id?

**Comment by jonbodner** [comment]
Did you try using a Querier instead of an Executor for the first parameter? I mean, it is technically an update, but I don't think that should make a difference. 

If it doesn't work, let me know and I'll take a look.

**Comment by michaelgmiller** [comment]
Seems to work :)
