### ISSUE TITLE
Select from list

### ISSUE THREAD

**Issue by michaelgmiller** [jonbodner/proteus#34]
Is there any way to do a query of the form:

`SELECT * from myTable where id IN (:list:)` ?

**Comment by jonbodner** [comment]
Yes, that should work automatically. If `:list:` is a slice of any type other than byte, it will be expanded out correctly. If you have a case where that isn't working, please let me know (sample code is best) so I can fix it.

**Comment by jonbodner** [comment]
Did you have any success? Can I close the issue?

**Comment by michaelgmiller** [comment]
Yup, works great!
