### ISSUE TITLE
SIGSEGV can occur when using structs with bad function return types

### ISSUE THREAD

**Issue by kalexmills** [jonbodner/proteus#46]
I recently tried to create and use a malformed function type like so. The return value is `error` whereas it should be `(int64, error)` to receive an error properly.
```
type UserDao struct {
  Insert func(ctx context.Context, e proteus.ContextExecutor, email string) error `proq:...`
}
```

I was able to instantiate this struct with `proteus.Build`, and everything worked out fine until I tried to use `Insert`, which failed with a confusing `SIGSEGV` at the point of failure.

**Comment by jonbodner** [comment]
Fixed in v0.12.0
