### ISSUE TITLE
proe tags do not work

### ISSUE THREAD

**Issue by michaelgmiller** [jonbodner/proteus#5]
The Build function only looks at proq tags in:
`
		query, ok := curField.Tag.Lookup("proq")
`
If I tag something with `proe` instead of `proq`, it will not be converted to a function, and will cause a null pointer exception. This means the examples are probably broken.

**Comment by michaelgmiller** [comment]
It seems like removing `proe` from the documentation but replacing with `proq` would work

**Comment by jonbodner** [comment]
Good catch; that was from an old version of Proteus. I'll fix the documentation.

**Comment by jonbodner** [comment]
The README has been updated. Thanks!

**Comment by michaelgmiller** [comment]
Awesome, thanks for the quick response. BTW, `proe` still exists in example2_test.go, example_test.go and proteus.go
