### ISSUE TITLE
Option to return values of type sql.Result to enable harvesting LastInsertId()

### ISSUE THREAD

**Issue by kalexmills** [jonbodner/proteus#52]
The `sql.Result` interface contains the LastInsertId() function, which can be important information useful for inserts/upserts.

It would be nice if there was a way that Proteus could return this information back to the caller. Perhaps by specifying `sql.Result` as a valid return type? My alternative right now is to execute something like `last_insert_rowid()` against my sqlite3 DB, which is prone to race conditions.

P.S. I keep posting 'nice-to-have' issues. Hope that's okay.
P.P.S. I'm highly motivated to raise a PR on this one, if maintainers are open to that.

**Comment by jonbodner** [comment]
I'd be happy with a PR to allow sql.Result as a valid return for a Executor. I'm very happy that someone is using Proteus 😄

**Comment by kalexmills-modo** [comment]
Yeah I decided CSV as hard-disk storage was.... er... cumbersome, so I transitioned github-vet to sqlite3 and using proteus is *so much* less code.
