### ISSUE TITLE
sql.NullString doesn't work

### ISSUE THREAD

**Issue by michaelgmiller** [jonbodner/proteus#6]
If I try to query a column of type `sql.NullString` with no value in it,  `buildStruct` fails with a message of the form:

`Expected nil, but got: &errors.errorString{s:"Unable to assign nil value to non-pointer struct field ToAddressLine2 of type sql.NullString"}`

**Comment by jonbodner** [comment]
Hrm; I'll build out a test case. Did you try using a `*string` type instead?

**Comment by michaelgmiller** [comment]
Sure thing, here's a test case:

```
package main

import (
    "database/sql"
    "fmt"
    "log"

    "github.com/jonbodner/proteus"
    _ "github.com/mattn/go-sqlite3"
)

type Product struct {
    Id   int            `prof:"id"`
    Name sql.NullString `prof:"name"`
    NullField sql.NullString `prof:"null_field"`
}

type ProductDao struct {
    Insert   func(e proteus.Executor, p Product) (int64, error) `proq:"insert into Product(name) values(:p.Name:)" prop:"p"`
    FindById func(e proteus.Querier, id int64) (Product, error) `proq:"select * from Product where id = :id:" prop:"id"`
}

func main() {
    productDao := ProductDao{}
    err := proteus.Build(&productDao, proteus.Sqlite)
    if err != nil {
        panic(err)
    }

    db, err := sql.Open("sqlite3", "./proteus_test.db")
    if err != nil {
        log.Fatal(err)
    }

    exec, err := db.Begin()
    if err != nil {
        panic(err)
    }

    _, err = exec.Exec("CREATE TABLE product(id INTEGER PRIMARY KEY, name VARCHAR(100), null_field VARCHAR(100))")
    if err != nil {
        panic(err)
    }

    gExec := proteus.Wrap(exec)

    p := Product{
        Name: sql.NullString{String: "hi", Valid: true},
    }

    rowId, err := productDao.Insert(gExec, p)
    if err != nil {
        panic(err)
    }
    fmt.Println(productDao.FindById(gExec, rowId))
}
```

**Comment by michaelgmiller** [comment]
Also just to be pedantic, I think this would be an issue for `NullBool`, `NullFloat64` and `NullInt64` in addition to `NullString`

**Comment by jonbodner** [comment]
Thanks! I thought I added support for types that implement `sql.Scanner`... must have missed something.

**Comment by michaelgmiller** [comment]
@jonbodner no problem! do you have an idea of whether this will be a quick fix? looking to get support for this to push a feature out - happy to help in any way I can!

**Comment by jonbodner** [comment]
It's a very quick fix. I should have it pushed up in a moment. I was doing a nil check before doing a check to see if a struct field implemented `sql.Scanner` for non-pointers. Now the checks are reversed.

**Comment by michaelgmiller** [comment]
@jonbodner you're the man! thanks for the rapid fire responses!!!
