### ISSUE TITLE
Intuitive way to check whether any rows were fetched for a single row query

### ISSUE THREAD

**Issue by michaelgmiller** [jonbodner/proteus#9]
Other than checking whether a field was set in a struct, is there a way to determine whether any rows were fetched in a SELECT for a single item fetch?

**Comment by jonbodner** [comment]
My suggestion is to make the return type for a single-row select a pointer to a struct. If the pointer is nil, then nothing was returned.  Maybe I need to add something to the docs on this...

**Comment by jonbodner** [comment]
I'll add a test case to make sure that this works sometime this weekend. In the stripped-down version of Proteus that was the basis for my talk at GopherCon, pointers to structs are the only thing you can return from a single-value select. 

The codebase for the talk was actually a re-write from scratch, so I need to make sure that it isn't a feature that's missing from the main project.

**Comment by michaelgmiller** [comment]
I just tested it and pointers with null checks work great! Thanks for the info!
